### ISSUE TITLE
"Provided schema does not match table" when running the fs-bq-schema-view script

### ISSUE THREAD

**Issue by gustavorochakv** [firebase/extensions#1300]
- Extension name: `firetore-bigquery-export` (the `gen-schema-views script`)
- Extension version: `firetore-bigquery-export@0.1.26`, latest `gen-schema-views script´ (I´ve also tried with 0.4.2)

We're updating our schema, and after deleting the previously generated views (as instructed by #423 and #646) running `npx @firebaseextensions/fs-bq-schema-views` fails with the following output:
```
{"code":400,"errors":[{"message":"Provided Schema does not match Table audit-backend:audit.audit_schema_fields_changelog. Cannot add fields (field: old_data)","domain":"global","reason":"invalid"}],"response":{"headers":{"alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","cache-control":"private","content-encoding":"gzip","content-type":"application/json; charset=UTF-8","date":"Wed, 16 Nov 2022 17:21:45 GMT","etag":"338qmb/WriADWLSvCyjq2w==","server":"ESF","transfer-encoding":"chunked","vary":"Origin, X-Origin, Referer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-xss-protection":"0"}},"message":"Provided Schema does not match Table audit-backend:audit.audit_schema_fields_changelog. Cannot add fields (field: old_data)"}
Provided Schema does not match Table audit-backend:audit.audit_schema_fields_changelog. Cannot add fields (field: old_data)
```

The script does create the audit_schema_fields_changelog view with most of the fields (it apparently stops while trying to add the old_data field), but it does not create the other one.

I've updated the schema a couple of times in the past following the exact same procedure without any issues. I'm using the exact same command as before:
```
npx @firebaseextensions/fs-bq-schema-views \
  --non-interactive \
  --project=audit-backend \
  --dataset=audit \
  --table-name-prefix=audit \
  --schema-files=./fields.json
```
I've also explicitly set the version to the previous one (`npx @firebaseextensions/fs-bq-schema-views@0.4.2` with the same result

**Comment by SayonB** [comment]
Same issue, same situation. Done this several times over the past few months and it worked, but I should mention that this time I'm trying to delete a column from the view.

**Comment by HerbertBodner** [comment]
Same here as well. I deleted the created schema and tried with `v0.4.2` and `v0.4.1` - same error

**Comment by cabljac** [comment]
Thanks! added to the board for consideration, will look into this

**Comment by alapeta** [comment]
Same issue there - 
I have tried to upgrade extension via Firebase Console to 0.1.27 (oldData is mentioned for this release as "added feature" - whatever it is - as there are no docs) - upgrade went ok, then I deleted both views in BQ, run again npx scripts...

Unfortunately the same error

**Comment by dackers86** [comment]
Please track the above for any updates. 

Although not the best workaround, removing the `old_data` column before generating any schemas could be a potential short term workaround?

**Comment by TangrisJones** [comment]
same issue here 🙏 looking forward for fix

**Comment by sabinayakc** [comment]
Facing same issue.

**Comment by dackers86** [comment]
An update has been added and published for this issue.

Please use to the latest version `0.4.4`.

Source: https://www.npmjs.com/package/@firebaseextensions/fs-bq-schema-views)

**Comment by FakhruddinAbdi** [comment]
Im trying to add a new field to the schema, but facing same issue, even with the last version `0.4.4`


```
{"code":400,"errors":[{"message":"Provided Schema does not match Table [..._changelog]. Cannot add fields (field: fbid)","domain":"global","reason":"invalid"}]
}
```

**Comment by FakhruddinAbdi** [comment]
> > Im trying to add a new field to the schema, but facing same issue, even with the last version `0.4.4`
> > ```
> > {"code":400,"errors":[{"message":"Provided Schema does not match Table [..._changelog]. Cannot add fields (field: fbid)","domain":"global","reason":"invalid"}]
> > }
> > ```
> 
> It worked for me, but I recreated the entire view instead of trying to add columns to an existing one as per the issues I listed on the OP. I also had to exicitly set it to 0.4.4 for it to work, but that was right after the fix was released, maybe that's no longer the case.

I see
I didn't try removing the current views, 
Actually, its a lot of work to link the new view with the current reports in the data studio
 I hoped we can bypass it somehow

**Comment by FakhruddinAbdi** [comment]
> As long as you recreate the views with the same name you won't need to relink anything on data studio: when you reconnect the data source it should recognize the updated schema (at the very least it has always worked that way for me)

Thanks, I did and it works, you right

**Comment by FakhruddinAbdi** [comment]
> @gustavorochakv @FakhruddinAbdi
> 
> Can you confirm that this is still an issue with the latest version.
> 
> Previously, I am assuming that you would not need to recreate the views when introducing a new field? But this is now a consistent issue?

Yes, it is still an issue with updating the schema directly
It doesn't allow to update the schema, instead, you have to remove the view manually, then run the script to recreate it

**Comment by gustavorochakv** [comment]
> > @gustavorochakv @FakhruddinAbdi
> > Can you confirm that this is still an issue with the latest version.
> > Previously, I am assuming that you would not need to recreate the views when introducing a new field? But this is now a consistent issue?
> 
> Yes, it is still an issue with updating the schema directly It doesn't allow to update the schema, instead, you have to remove the view manually, then run the script to recreate it

When I created this issue the error was happening even when recreating the views.  This was fixed with 0.4.4. I haven't tried to introduce a new field without recreating the views on 0.4.4.

**Comment by otopba** [comment]
@dackers86 yeah still an issue with the latest version

```
Provided Schema does not match Table XXX_changelog. Cannot add fields (field: moderated)"
```

**Comment by JarnoRFB** [comment]
I am still getting this error with `0.4.7`. It would be great if one could update (add/delete columns) existing schemas without manually deleting the tables, or if we could have an option in the CLI to delete the existing tables when recreating the schema views.

**Comment by christophe-g** [comment]
@dackers86  - is it possible to re-open this issue ?

Still getting this error with 0.4.10
