### ISSUE TITLE
Error when running fs-bq-import-collection. PartialFailureError

### ISSUE THREAD

**Issue by joaqcid** [firebase/extensions#192]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: ** fs-bq-import-collection ** 
- Extension version: ** N/A **
- Configuration values (redact info where appropriate):
  - ** project: pats-production **
  - ** collection: oilworx-customers **
  - ** dataset: firestore_export **
  - ** table_prefix: oilworx_customers **

### [REQUIRED] Step 3: Describe the problem
When running `npx @firebaseextensions/fs-bq-import-collection` i get an error and no rows are imported. I tried with several collections and projects and none of them is working. This script worked for me a week ago.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.
```
Importing data from Cloud Firestore Collection: oilworx-customers, to BigQuery Dataset: firestore_export, Table: oilworx_customers_raw_changelog
BigQuery dataset already exists: firestore_export
BigQuery table with name oilworx_customers_raw_changelog already exists in dataset firestore_export!
View with id oilworx_customers_raw_latest already exists in dataset firestore_export.
Inserting 100 row(s) of data into BigQuery
Error importing Collection to BigQuery: PartialFailureError
```

##### Expected result
Documents imported to bigquery

##### Actual result
No documents were imported to bigquery

**Comment by cedgen** [comment]
I have the exact same error. And it also worked for me some weeks ago.

**Comment by dperezrada** [comment]
I was having the same problem.
This is [related to](https://github.com/googleapis/nodejs-bigquery/issues/612) 

The version of the bigquery "@google-cloud/bigquery": "^2.1.0", is a really old one. I had a newer version, I was having problem with this file `firestore-bigquery-change-tracker/src/bigquery/index.ts`. In particular, the way they ser calling the `insert(payload, options)` It seems that now is `insert(rows)`.

Try to reinstall the dependencies, and retry.

**Comment by cedgen** [comment]
Unfortunately this is not solving the issue for me. I reinstalled the dependencies but still get the same error.

**Comment by joaqcid** [comment]
i was able to import rows updating bigquery lib to "@google-cloud/bigquery": "^4.7.0", and changing the insert method to do : 
`await table.insert(rows, options);` where options are
```
const options = {
      skipInvalidRows: false,
      ignoreUnkownValues: false,
      raw: true
    } as InsertRowsOptions;
```

also created a PR to address this issue, @IanWyszynski can you look at it and let me know if  it looks good to you? thanks!

**Comment by geoffbullen** [comment]
Hi @joaqcid 

You seem to have solved this, but I wasn't able to replicate what you did.   I cloned the repo and updated the dependecy to 4.7, but that didn't seem to help when I ran it again.  

Could you do an idiots guide version of your above comment please?

**Comment by asikand** [comment]
I made the changes suggested in the PR to the index.js file (not using Typescript) and I updated the dependency to 4.7 but I'm still getting the error.

**Comment by joaqcid** [comment]
hi all, 

i creted a branch "run-manual-import" on my fork for to run it manually, https://github.com/joaqcid/extensions

from there, you need to 
- npm install in firestore-bigquery-change-tracker folder (dont mind the errors)
- npm install in scripts/import folder
- npm run import

hope this helps

**Comment by asikand** [comment]
@joaqcid Do I want to use the fix-bq-import fork or the run-manual-import fork?

**Comment by joaqcid** [comment]
run-manual-import

**Comment by geoffbullen** [comment]
@joaqcid.   Thanks a heap, worked a treat...

**Comment by tptshoe** [comment]
Hi @joaqcid, thanks for posting this!! Unfortunately I just followed the instructions exactly and came out with the same error. Here's the full log output:

`
0 info it worked if it ends with ok
1 verbose cli [ '/Users/markflegg/.nvm/versions/node/v10.18.1/bin/node',
1 verbose cli   '/Users/markflegg/.nvm/versions/node/v10.18.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'import' ]
2 info using npm@6.13.4
3 info using node@v10.18.1
4 verbose run-script [ 'preimport', 'import', 'postimport' ]
5 info lifecycle @firebaseextensions/fs-bq-import-collection@0.1.3~preimport: @firebaseextensions/fs-bq-import-collection@0.1.3
6 info lifecycle @firebaseextensions/fs-bq-import-collection@0.1.3~import: @firebaseextensions/fs-bq-import-collection@0.1.3
7 verbose lifecycle @firebaseextensions/fs-bq-import-collection@0.1.3~import: unsafe-perm in lifecycle true
8 verbose lifecycle @firebaseextensions/fs-bq-import-collection@0.1.3~import: PATH: /Users/markflegg/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/markflegg/programming/shadda/extensions/firestore-bigquery-export/scripts/import/node_modules/.bin:/Users/markflegg/programming/google-cloud-sdk/bin:/Users/markflegg/.nvm/versions/node/v10.18.1/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/markflegg/programming/flutter/bin
9 verbose lifecycle @firebaseextensions/fs-bq-import-collection@0.1.3~import: CWD: /Users/markflegg/programming/shadda/extensions/firestore-bigquery-export/scripts/import
10 silly lifecycle @firebaseextensions/fs-bq-import-collection@0.1.3~import: Args: [ '-c', 'node ./lib/index.js' ]
11 silly lifecycle @firebaseextensions/fs-bq-import-collection@0.1.3~import: Returned: code: 1  signal: null
12 info lifecycle @firebaseextensions/fs-bq-import-collection@0.1.3~import: Failed to exec import script
13 verbose stack Error: @firebaseextensions/fs-bq-import-collection@0.1.3 import: `node ./lib/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/markflegg/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/markflegg/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @firebaseextensions/fs-bq-import-collection@0.1.3
15 verbose cwd /Users/markflegg/programming/shadda/extensions/firestore-bigquery-export/scripts/import
16 verbose Darwin 19.3.0
17 verbose argv "/Users/markflegg/.nvm/versions/node/v10.18.1/bin/node" "/Users/markflegg/.nvm/versions/node/v10.18.1/bin/npm" "run" "import"
18 verbose node v10.18.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error @firebaseextensions/fs-bq-import-collection@0.1.3 import: `node ./lib/index.js`
22 error Exit status 1
23 error Failed at the @firebaseextensions/fs-bq-import-collection@0.1.3 import script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Thanks for any help you can give!!

-mf

> i creted a branch "run-manual-import" on my fork for to run it manually, https://github.com/joaqcid/extensions
> 
> from there, you need to
> 
> * npm install in firestore-bigquery-change-tracker folder (dont mind the errors)
> * npm install in scripts/import folder
> * npm run import
> 
> hope this helps

**Comment by joaqcid** [comment]
@tptshoe i cant understand the error in the logs, try clearing all node_modules folders from the firebase/extensions and re-run npm install only under 
/firestore-bigquery-export/firestore-bigquery-change-tracker
/firestore-bigquery-export/scripts/import

then run npm import under

/firestore-bigquery-export/scripts/import

**Comment by madhudvs** [comment]
@joaqcid  i tried your solution 
![Screenshot 2020-02-13 at 12 45 15 PM](https://user-images.githubusercontent.com/863475/74410259-b643a400-4e5e-11ea-8b6f-74ce03d3cd07.png)

getting this error  , it will be great if you can look into this

**Comment by joaqcid** [comment]
hi @madhudvs are you using the branch from my fork? looking at the logs it seems like you are using a different versio

**Comment by madhudvs** [comment]
Hi @jacquetd  am cloning from https://github.com/joaqcid/extensions
and did these steps
    npm install in firestore-bigquery-change-tracker 
    npm install in scripts/import folder
    npm run import in import

**Comment by cedgen** [comment]
@joaqcid I see the same error as @madhudvs, maybe you can go in a bit more detail on how to follow your fix. Thank you in advance :)

**Comment by fischermatte** [comment]
@joaqcid thx a lot, this fix saved my day. by following those steps it worked with my firebase projects.

**Comment by joaqcid** [comment]
are you executing steps on branch "run-manual-import" @cedgen @madhudvs ?

**Comment by madhudvs** [comment]
@joaqcid  @cedgen    the specific branch "run-manual-import" @ https://github.com/joaqcid/extensions fixed the issue ,  now i am able to import

**Comment by cedgen** [comment]
@joaqcid  yes, I downloaded the files on the branch "run-manual-import" and than did the steps but its still not working

**Comment by cedgen** [comment]
MacBook-Pro:import User$ npm run import

> @firebaseextensions/fs-bq-import-collection@0.1.3 import /Users/user/node_modules/extensions-run-manual-import/firestore-bigquery-export/scripts/import
> node ./lib/scripts/import/src/index.js

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/Users/user/node_modules/extensions-run-manual-import/firestore-bigquery-export/scripts/import/lib/scripts/import/src/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @firebaseextensions/fs-bq-import-collection@0.1.3 import: `node ./lib/scripts/import/src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @firebaseextensions/fs-bq-import-collection@0.1.3 import script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-02-14T10_34_01_803Z-debug.log

**Comment by joaqcid** [comment]
@cedgen looks like it didn't compile scripts/import, and not finding the code to run. do you get any errors when you run npm install under scripts/import?

**Comment by sourcec0de** [comment]
@joaqcid this was a big help!!!!

```sh
git clone git@github.com:joaqcid/extensions.git
cd extensions
git checkout run-manual-import
cd firestore-bigquery-export/firestore-bigquery-change-tracker
npm i
cd ../scripts/import
npm i
npm run import
```

**Comment by cedgen** [comment]
@joaqcid no errors when doing npm install at scripts/import, but still get this error:
`13 verbose stack Error: @firebaseextensions/fs-bq-import-collection@0.1.3 import: `node ./lib/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @firebaseextensions/fs-bq-import-collection@0.1.3
 `

**Comment by joaqcid** [comment]
sorry @cedgen cant tell from the logs, what the problem might be, would recommend to start from a clean folder and see if that fixes it for you.

btw im running on node v10.17.0

**Comment by stari4ek** [comment]
@sourcec0de ,
got compilation errors during install:

```
$ npm i

> @firebaseextensions/firestore-bigquery-change-tracker@1.0.1 prepare /home/astar/dev/extensions/firestore-bigquery-export/firestore-bigquery-change-tracker
> npm run build


> @firebaseextensions/firestore-bigquery-change-tracker@1.0.1 build /home/astar/dev/extensions/firestore-bigquery-export/firestore-bigquery-change-tracker
> npm run clean && npm run compile


> @firebaseextensions/firestore-bigquery-change-tracker@1.0.1 clean /home/astar/dev/extensions/firestore-bigquery-export/firestore-bigquery-change-tracker
> rimraf functions/lib


> @firebaseextensions/firestore-bigquery-change-tracker@1.0.1 compile /home/astar/dev/extensions/firestore-bigquery-export/firestore-bigquery-change-tracker
> tsc

src/test/bigquery/snapshot.spec.ts:47:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

47 describe("latest snapshot view sql generation", () => {
   ~~~~~~~~

src/test/bigquery/snapshot.spec.ts:48:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

48   it("should generate the epxected sql", async () => {
     ~~

src/test/bigquery/snapshot.spec.ts:60:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

60   it("should generate correct sql with no groupBy columns", async () => {
     ~~

src/test/bigquery/snapshot.spec.ts:72:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

72   it("should throw an error for empty group by columns", async () => {
     ~~

src/test/bigquery/snapshot.spec.ts:79:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

79   it("should throw an error for empty timestamp field", async () => {
     ~~


Found 5 errors.
```

**Comment by joshuarcher** [comment]
Also having this issue after node installs. Can anyone from the Firebase team merge this in?

**Comment by russellwheatley** [comment]
A fix has been merged in #197

**Comment by FredvanRijswijk** [comment]
How to use this fix? `npx @firebaseextensions/fs-bq-import-collection `

**Comment by puppybits** [comment]
I'm still not able to use `npx @firebaseextensions/fs-bq-import-collection`. The fork worked (but required editing to use collectionGroup for the query.

**Comment by laurenzlong** [comment]
Hi, the package has been updated on NPM, sorry for the delay!
