### ISSUE TITLE
🐛 Bug Report: Emails Not Triggering in Latest Version of "Trigger Email from Firestore" Extension 0.1.35

### ISSUE THREAD

**Issue by vamshi-i2i** [firebase/extensions#2279]
### [READ] Step 1: Are you in the right place?
Yes, this issue is specifically for the "Trigger Email from Firestore" extension.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-send-email**
- Extension version: **(Latest Version, 0.1.35)**
- Configuration values:
  - **SMTP Settings:** Verified and working  
  - **Firestore Collection:** Configured correctly

#### Steps to reproduce:

After updating to the latest version of the "Trigger Email from Firestore" extension, emails are no longer being triggered, and **there are no error logs**. The issue is reproducible.

1. Install the latest version of the extension.
2. Add a new Firestore document to trigger an email.
3. Observe that the email is **not sent** and **no errors appear in logs**.

##### Expected result
- Email should be sent when a Firestore document is added.

##### Actual result
- No email is triggered.
- No error logs appear in Firebase logs.

### Screenshots
- **Latest version of the extension:*0.1.35*
<img width="1294" alt="Image" src="https://github.com/user-attachments/assets/70e6c85d-43b5-4a0b-8e32-f68332c9906e" />

- **Old version of the extension (working):*0.1.34*

<img width="1281" alt="Image" src="https://github.com/user-attachments/assets/aef25060-5ad3-4030-bc8c-0e677e6c7b1f" />

### Recommended Next Steps
Since this extension is developed by a different team, I recommend checking the extension's GitHub repository to see if others have reported similar issues. Please confirm if this is a **bug with the latest release** and provide guidance on resolving it.

Let me know if more information is needed.

Thanks,  
Vamshi

**Comment by cabljac** [comment]
Hi there, thanks for opening this.

What SMTP provider are you using? Sendgrid, or something else?

**Comment by CorieW** [comment]
I haven't been able to reproduce this using SendGrid or Gmail as the provider. More information is necessary for further investigation into this.

**Comment by cabljac** [comment]
@vamshi-i2i  can you provide any logs you can see? perhaps there's an error message which will provide insight.

**Comment by cabljac** [comment]
@vamshi-i2i Also can you tell us what your smtp host is? or at least what provider you're using?

**Comment by vamshi-i2i** [comment]
> [@vamshi-i2i](https://github.com/vamshi-i2i) Also can you tell us what your smtp host is? or at least what provider you're using?

Previously, it is network solutions later we changed it to the AWS smtp, these issue was reproduce on my end and firebase support too but it was resolved after 48 hrs of updated extension. Now we are able to send the emails from email trigger extension. Thank you!

**Comment by vamshi-i2i** [comment]
> [@vamshi-i2i](https://github.com/vamshi-i2i) can you provide any logs you can see? perhaps there's an error message which will provide insight.

Sorry, Actually when we updated to the version 0.1.35, we are unable to see the logs too and execute the function too. It was resolved after 2 to 3 days of time after the update. Still curious to know How these happen when it is updated or it might take 3 days to update?

**Comment by cabljac** [comment]
Hi @vamshi-i2i, i'll reopen this as it sounds like you still have the issue.

Can you provide your extension config (redact anything sensitive of course)

**Comment by Pwntus** [comment]
Having the same issue now.

Fresh install, the first installation issue:
```
; RESOURCE_ERROR at /deployments/firebase-ext-firestore-send-email/resources/processQueue: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Gen1 operation for function projects/<redacted>/locations/europe-central2/functions/ext-firestore-send-email-processQueue failed: Build failed: Access to bucket gcf-sources-<redacted>-europe-central2 denied. You must grant Storage Object Viewer permission to <redacted>-compute@developer.gserviceaccount.com. If you are using VPC Service Controls, you must also grant it access to your service perimeter.\n."}
```

After granting the principal `<redacted>-compute@developer.gserviceaccount.com` with `Storage Object Viewer` permission to the bucket, I tried re-installing. The re-installation was seemingly successful in the Firebase console, but if I inspect the cloud function `ext-firestore-send-email-processQueue` it failed to deploy because it already existed.

The root cause seems to be the missing permission for the service role to access the bucket. Upon fixing that permission issue, the extension is re-deployed but fail to update a function because it already exists.

I managed to bypass this by deleting the function before trying to re-install the extension after a clean install. This however resulted in a failed build, where the logs are not viewable `Build failed: Build error details not available. Please check the logs at: <URL>`

**Comment by cabljac** [comment]
Thanks for the extra context here. It's strange that it now needs permission to a bucket, this extension shouldn't be interacting with storage itself. 

I'll raise this with the team and see if there's some platform issue we're unaware of.
