### ISSUE TITLE
"Map Datatypes" not working for gen-schema-view

### ISSUE THREAD

**Issue by newadays** [firebase/extensions#267]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **gen-schema-view*
- Extension version: **latest**
- Configuration values (redact info where appropriate):
  - **firestore schema**
```
"mainImage": {
  "main": "url1",
  "small": "url2",
  "medium": "url3",
  "thumbnail": "url4"
}
```

  - **Schema.json**
```
{
  "fields": [
    {
      "fields": [
 { "name": "main", "type": "string" }, { "name": "medium", "type": "string" }, { "name": "small", "type": "string" }, { "name": "thumbnail", "type": "string" }
      ],
      "name": "mainImage",
      "type": "map"
    }
  ]
}
```

### [REQUIRED] Step 3: Describe the problem
1. Firestore export to BigQuery was successful
2. Generate VIEWS based on the BigQuery Schema
#### Steps to reproduce:

1. Create a similar document in Firestore and use the [fs-bq-import-collection](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md) to export to BigQuery

2. Use the [gen-schema-view](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md) to generate a BigQuery View.

What happened? How can we make the problem occur?
ERROR:
`{"code":400,"errors":[{"message":"Provided Schema does not match Table PROJECT_ID:firestore_export.DATASET_ID_schema_schema_changelog. Cannot add fields (field: mainImage_main)","domain":"global","reason":
"invalid"}],"message":"Provided Schema does not match Table PROJECT_ID:firestore_export.DATASET_ID_schema_schema_changelog. Cannot add fields (field: mainImage_main)"}
Provided Schema does not match Table PROJECT_ID:firestore_export.DATASET_ID_schema_schema_changelog. Cannot add fields (field: mainImage_main)`

It seems the map (JSON) was not interpreted correctly.
##### Expected result
JSON field that corresponds to the MAP datatype in Firestore
##### Actual result
ERROR - appended "_" to the map fields and could not find it in the existing RAW export in BigQuery.

**Comment by newadays** [comment]
File additional issue as recommended by @laurenzlong. See previous comments [here](https://github.com/firebase/extensions/pull/257)

**Comment by laurenzlong** [comment]
@russellwheatley would you mind taking a look? Thanks!

**Comment by russellwheatley** [comment]
I believe the error has been fixed now as I've tried running the `npx @firebaseextensions/fs-bq-schema-views` with the above mentioned schema and data structure, and I was able to successfully create the table. Below are the console logs showing the data being accessed using dot notation whilst correctly using the underscore for the column names:
![Screenshot 2020-04-20 at 12 54 45](https://user-images.githubusercontent.com/16018629/79748905-1e52b280-8306-11ea-91ae-0f25eacb191a.png)

Here is the data in the resulting view table:
<img width="558" alt="Screenshot 2020-04-20 at 12 57 56" src="https://user-images.githubusercontent.com/16018629/79749139-95884680-8306-11ea-9291-401a43d2fafb.png">

Could you try running `npx @firebaseextensions/fs-bq-schema-views` and let me know if you still get the same error, please @newadays?

**Comment by newadays** [comment]
@russellwheatley Still experiencing the same issue. I was able import the Firestore schema using [export script](fs-bq-import-collection) into bigQuery  and query the raw logs successfully as shown below. However, when running [generate schema views](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md), it is trying to find the fields that are not there by appending '_' .
![firestore_schema](https://user-images.githubusercontent.com/14118614/79779829-9ddd8300-8300-11ea-947a-c85b1827a88a.jpeg)

![firestore_bq_export](https://user-images.githubusercontent.com/14118614/79779558-30c9ed80-8300-11ea-9836-02a951db6931.jpeg)

![error_bq_schema_views](https://user-images.githubusercontent.com/14118614/79778599-9cab5680-82fe-11ea-9b82-7664e1f9568c.jpeg)

**Comment by russellwheatley** [comment]
Interesting. It works for me so now it's a case of reproducing your error. I noticed that you have a `schema.json` file with 110 lines. Have you tried with just the portion causing the error? 

i.e.
```
{
  "fields": [
    {
      "name": "mainImage",
      "type": "map",
      "fields": [
        { "name": "main", "type": "string" },
        { "name": "medium", "type": "string" },
        { "name": "small", "type": "string" },
        { "name": "thumbnail", "type": "string" }
      ]
    }
  ]
}

```

If yes, do you mind sharing your schema for me to test, please?

**Comment by newadays** [comment]
That's strange, I am getting the same issue. Here's the schema.json.
```
{
  "fields": [
    {
      "name": "currency",
      "type": "string"
    },
    {
      "name": "discount",
      "type": "string"
    },
    {
      "name": "discountedPrice",
      "type": "string"
    },
    {
      "name": "featuredImage",
      "type": "string"
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "lastUpdate",
      "type": "string"
    },
    {
      "name": "likes",
      "type": "number"
    },
    {
      "name": "location",
      "type": "string"
    },
    {
      "name": "mainImage",
      "type": "map",
      "fields": [
        { "name": "main", "type": "string" },
        { "name": "medium", "type": "string" },
        { "name": "small", "type": "string" },
        { "name": "thumbnail", "type": "string" }
      ]
    },
    {
      "name": "productCategory",
      "type": "array"
    },
    {
      "name": "productDescription",
      "type": "string"
    },
    {
      "name": "productImages",
      "type": "array"
    },
    {
      "name": "productName",
      "type": "string"
    },
    {
      "name": "productPrice",
      "type": "string"
    },
    {
      "name": "productStock",
      "type": "string"
    },
    {
      "name": "productVariant",
      "type": "array"
    },
    {
      "name": "productWeight",
      "type": "string"
    },
    {
      "name": "sellerFullName",
      "type": "string"
    },
    {
      "name": "sellerId",
      "type": "string"
    },
    {
      "name": "sku",
      "type": "string"
    },
    {
      "name": "slug",
      "type": "string"
    },
    {
      "name": "storeName",
      "type": "string"
    }
  ]
}
```

**Comment by newadays** [comment]
Hi @russellwheatley - Did you get a chance to try it out the schema.json ?

**Comment by russellwheatley** [comment]
Hey @newadays, your schema worked fine for me. 

I was able to recreate your error however:
![Screenshot 2020-04-23 at 08 17 17](https://user-images.githubusercontent.com/16018629/80071493-a3bfa800-853c-11ea-8c7e-e4f5524771f5.png)

I did this by having a property that didn't match the schema. i.e.
```
{
      "name": "mainImage",
      "type": "map",
      "fields": [
        { "name": "thumbnail", "type": "string" }
      ]
    },
```

In my dataset, I have `thumbnail` as a number.
<img width="518" alt="Screenshot 2020-04-23 at 08 44 17" src="https://user-images.githubusercontent.com/16018629/80072788-a3c0a780-853e-11ea-9528-a5e2a492a8d1.png">

The mismatch of types caused an error. Do you mind checking the `mainImage.main` property in your dataset you're creating the view from, and checking to see if any of them are not a string?

**Comment by newadays** [comment]
@russellwheatley - All the entries are string. See sample provided earlier [here](https://github.com/firebase/extensions/issues/267#issuecomment-616696109)

**Comment by russellwheatley** [comment]
One way you could test if it is something in your current dataset is by creating a new Big Query extension with a different dataset & collection. Add a new record in the new collection: 
```
"mainImage": {
  "main": "url1",
  "small": "url2",
  "medium": "url3",
  "thumbnail": "url4"
}
```

Run `gen-schema-view` script with your schema.

**Comment by sommes54** [comment]
Issue resolved by manually running the query. Thanks @russellwheatley

**Comment by newadays** [comment]
Manually ran the Query which resolved the issue. Thank you @russellwheatley

**Comment by russellwheatley** [comment]
Glad you were able to find a solution, @newadays 👍
