### ISSUE TITLE
Cannot read property 'sendMail' of undefined

### ISSUE THREAD

**Issue by yamankatby** [firebase/extensions#954]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-send-email**
- Extension version: **0.1.16**
- Configuration values (redact info where appropriate):

![Screen Shot 2022-04-28 at 07 17 40](https://user-images.githubusercontent.com/35961879/165675889-86cbdaaf-0d3d-4f5f-af5c-f26e31486f3f.png)

### [REQUIRED] Step 3: Describe the problem
![Screen Shot 2022-04-28 at 07 21 20](https://user-images.githubusercontent.com/35961879/165675983-159c6c69-ca0e-4f67-909b-8698c10d0e4e.png)

![Screen Shot 2022-04-28 at 07 23 46](https://user-images.githubusercontent.com/35961879/165676187-1454d452-91a4-495b-8a06-31f2e2d09b77.png)

#### Steps to reproduce:

- Install the extension either by console or cli
- Send email

##### Expected result

To be sent or to show any clear error message/log

**Comment by danhockley** [comment]
Did you find a solution to this?

**Comment by yamankatby** [comment]
Hi @danhockley,
No, not yet. But I'll be working on fixing this soon, so please consider providing me with any information you think might be useful.

**Comment by nwatab** [comment]
Same here. I tried password in URI (backward compat) and secure password. They didn't work at 0.1.17.

**Comment by debungle-it** [comment]
I have the same issue - Adding myself so that I have visibility into the status

**Comment by CeccoCQ** [comment]
Same issue, how I can rollback to previous version?

**Comment by dackers86** [comment]
Hi @CeccoCQ 

The only current way to roll back is to, find a specific commit and use the cli to update using...

`firebase ext:update {ext-name} . --project={project_name}`

You could as an alternative, create a new installation and use the a specified version to create a new instance.

`firebase install firestore-send-email@{version} --project={project_name}`

**Comment by CeccoCQ** [comment]
Hi @dackers86 ,
I understand, but I've a question: can the problem be solved with a future update of the extension?

**Comment by CeccoCQ** [comment]
@dackers86 great! Thanks

**Comment by michalkubizna** [comment]
This is not solved. I am still getting this message: "Cannot read property 'sendMail' of undefined".

**Comment by dackers86** [comment]
HI @mateuszsoppo.

Can you confirm what version of the extension you are running? And also an example of the mail document (and template) that you are attempting to process. Thanks!

**Comment by michalkubizna** [comment]
I am using version 0.1.23. I made a typo by not including the '@' symbol. So instead of 'smtps://${email}@smtp.gmail.com:465', I wrote 'smtps://${email}:smtp.gmail.com:465'. But the error message wasn't very helpful.

**Comment by dackers86** [comment]
Thanks @michalkubizna.

This has highlighted a bug on line https://github.com/firebase/extensions/blob/0696bfe518b318c4530700f348a4a97bd7c55942/firestore-send-email/functions/src/index.ts#L274.

We do test for valid smtp url, but will require an update to warn the user if this is invalid when sending emails.

**Comment by dackers86** [comment]
Issue added : https://github.com/firebase/extensions/issues/1472

**Comment by biomichael** [comment]
I solved it by passing smtp credentials URI encoded. so instead of this:
smtps://username@gmail.com:password@smtp.gmail.com:465
you would pass
smtps://username%40gmail.com%3Apassword@smtp.gmail.com:465
Note: if you are using gmail server you might need to set up a App Password which is a string of 16 random characters in 4 groups.
